[build]
  command = "npm run build"
  publish = "dist"

# Production site (main domain)
[context.production]
  environment = { NODE_ENV = "production", SITE_CONFIG = "main" }

# S5T9U3V7 subdomain site
[context.s5t9u3v7]
  environment = { NODE_ENV = "production", SITE_CONFIG = "s5t9u3v7" }

# Staging site (staging subdomain)
[context.staging]
  environment = { NODE_ENV = "staging", SITE_CONFIG = "staging" }

# Development site (dev subdomain)
[context.deploy-preview]
  environment = { NODE_ENV = "development", SITE_CONFIG = "dev" }

# Branch deployments
[context.branch-deploy]
  environment = { NODE_ENV = "development", SITE_CONFIG = "dev" } 